import { Tag } from "@/utils/interfaces";

export const tags: Tag[] = [
  { id: "1", name: "Botox", icon: "Syringe", isActive: true },
  { id: "2", name: "Preenchimento Facial", icon: "Smile", isActive: false },
  { id: "3", name: "Peeling Químico", icon: "Sparkles", isActive: false },
  { id: "4", name: "Limpeza de Pele", icon: "Droplet", isActive: true },
  { id: "5", name: "Microagulhamento", icon: "Needle", isActive: false },
  { id: "6", name: "Laser Facial", icon: "Sun", isActive: false },
  { id: "7", name: "Depilação a Laser", icon: "Scissors", isActive: false },
  { id: "8", name: "Lipo de Papada", icon: "Activity", isActive: false },
  { id: "9", name: "Criolipólise", icon: "Snowflake", isActive: false },
  { id: "10", name: "Drenagem Linfática", icon: "Droplets", isActive: false },
  { id: "11", name: "Massagem Relaxante", icon: "Hand", isActive: true },
  { id: "12", name: "Massagem Modeladora", icon: "Move", isActive: false },
  { id: "13", name: "Rejuvenescimento Facial", icon: "Sparkle", isActive: false },
  { id: "14", name: "Tratamento de Estrias", icon: "LineChart", isActive: false },
  { id: "15", name: "Tratamento de Celulite", icon: "Grid", isActive: false },
  { id: "16", name: "Harmonização Facial", icon: "Gem", isActive: false },
  { id: "17", name: "Clareamento de Manchas", icon: "Highlighter", isActive: false },
  { id: "18", name: "Ozonioterapia", icon: "Wind", isActive: false },
  { id: "19", name: "Radiofrequência", icon: "Wifi", isActive: false },
  { id: "20", name: "Ultrassom Estético", icon: "Waveform", isActive: false },
  { id: "21", name: "Design de Sobrancelha", icon: "Pen", isActive: true },
  { id: "22", name: "Micropigmentação", icon: "Brush", isActive: false },
  { id: "23", name: "Alongamento de Cílios", icon: "Eye", isActive: false },
  { id: "24", name: "Lifting Facial", icon: "ArrowUpCircle", isActive: false },
  { id: "25", name: "Toxina Botulínica", icon: "FlaskRound", isActive: false },
  { id: "26", name: "Tratamento Capilar", icon: "ScissorsSquare", isActive: false },
  { id: "27", name: "Skinbooster", icon: "DropletPlus", isActive: false },
  { id: "28", name: "Bioestimulador", icon: "Zap", isActive: false },
  { id: "29", name: "Reiki", icon: "Flower2", isActive: false },
  { id: "30", name: "Spa Day", icon: "Heart", isActive: true },
   { id: "31", name: "Acupuntura Estética", icon: "Cross", isActive: false },
  { id: "32", name: "Terapia com Ventosa", icon: "CircleDashed", isActive: false },
  { id: "33", name: "Hidratação Facial", icon: "Droplet", isActive: true },
  { id: "34", name: "Peeling de Diamante", icon: "Diamond", isActive: false },
  { id: "35", name: "Tratamento para Flacidez", icon: "ActivitySquare", isActive: false },
  { id: "36", name: "Massagem com Pedras Quentes", icon: "Mountain", isActive: false },
  { id: "37", name: "Tratamento para Rugas", icon: "Pilcrow", isActive: false },
  { id: "38", name: "Máscara Facial", icon: "Mask", isActive: false },
  { id: "39", name: "Spa dos Pés", icon: "Footprints", isActive: false },
  { id: "40", name: "Spa das Mãos", icon: "HandMetal", isActive: false },
  { id: "41", name: "Esfoliação Corporal", icon: "Layers", isActive: false },
  { id: "42", name: "Banho de Lua", icon: "Moon", isActive: false },
  { id: "43", name: "Tratamento Detox", icon: "Recycle", isActive: false },
  { id: "44", name: "Terapia Capilar", icon: "DropletSlash", isActive: false },
  { id: "45", name: "Massagem Ayurvédica", icon: "Leaf", isActive: false },
]
