import LayoutWrapper from '@/components/LayoutWrapper'
import '@/lib/dayjs'
import { SITE_NAME } from '@/utils/constants'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'

import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
  fallback: ['system-ui', 'Arial', 'sans-serif'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
  fallback: ['monospace'],
})

export const metadata: Metadata = {
  title: SITE_NAME,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NuqsAdapter>
          <LayoutWrapper>{children}</LayoutWrapper>
          <Toaster
            richColors
            position="top-center"
          />
        </NuqsAdapter>
      </body>
    </html>
  )
}
